"""
PULSE - Azure AI Content Safety Service
Provides prompt shield, PII detection, and content moderation via Azure AI Content Safety.
Falls back to rule-based scanning when Azure Content Safety is unavailable.
"""

import logging
import re
from datetime import datetime
from typing import Any

from app.config import settings

logger = logging.getLogger("pulse.service.content_safety")

# ── PII Patterns ─────────────────────────────────────────────
_PII_PATTERNS = {
    "ssn": (re.compile(r"\b\d{3}-\d{2}-\d{4}\b"), "Social Security Number"),
    "credit_card": (re.compile(r"\b(?:4\d{3}|5[1-5]\d{2}|3[47]\d{2}|6011)[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}\b"), "Credit Card Number"),
    "email": (re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b"), "Email Address"),
    "phone": (re.compile(r"\b(?:\+1[\s-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\b"), "Phone Number"),
    "ip_address": (re.compile(r"\b(?:(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\.){3}(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]?\d)\b"), "IP Address"),
}

# ── Prompt Injection Patterns ────────────────────────────────
_INJECTION_PATTERNS = [
    re.compile(r"ignore\s+(all\s+)?(previous|above|prior)\s+(instructions?|prompts?|rules?)", re.IGNORECASE),
    re.compile(r"(disregard|forget)\s+(all\s+)?(previous|your|the)\s+(instructions?|rules?|guidelines?)", re.IGNORECASE),
    re.compile(r"you\s+are\s+now\s+(a|an|in)\s+", re.IGNORECASE),
    re.compile(r"act\s+as\s+(if\s+)?(you\s+)?(are|were)\s+", re.IGNORECASE),
    re.compile(r"(system|admin)\s*:\s*", re.IGNORECASE),
    re.compile(r"<\s*(?:system|prompt|instruction)\s*>", re.IGNORECASE),
    re.compile(r"\[INST\]|\[/INST\]|\[SYSTEM\]", re.IGNORECASE),
    re.compile(r"do\s+not\s+follow\s+(your|the)\s+(original|initial|previous)", re.IGNORECASE),
    re.compile(r"override\s+(your|the|all)\s+(safety|content|moderation)", re.IGNORECASE),
    re.compile(r"jailbreak|DAN\s+mode|developer\s+mode|evil\s+mode", re.IGNORECASE),
    re.compile(r"pretend\s+(you|to)\s+(are|be|have)\s+(no|without)", re.IGNORECASE),
]

# ── Harmful Content Keywords ────────────────────────────────
_HARMFUL_PATTERNS = [
    re.compile(r"\b(bomb\s+making|how\s+to\s+make\s+a\s+bomb|explosives?\s+recipe)\b", re.IGNORECASE),
    re.compile(r"\b(hack\s+into|breach\s+security|exploit\s+vulnerability)\b", re.IGNORECASE),
    re.compile(r"\b(kill\s+yourself|suicide\s+method|self.?harm\s+guide)\b", re.IGNORECASE),
]


async def scan_content(text: str, content_type: str = "input") -> dict[str, Any]:
    """
    Scan text for security threats.
    Returns a structured result with threat categories and severity.
    
    content_type: 'input' (inbound from user) or 'output' (generated by AI)
    """
    result = {
        "safe": True,
        "scan_type": content_type,
        "timestamp": datetime.utcnow().isoformat(),
        "threats": [],
        "pii_detected": [],
        "injection_detected": False,
        "harmful_content": False,
        "risk_score": 0.0,   # 0.0 = safe, 1.0 = critical
    }

    if not text or not text.strip():
        return result

    # ── Check for prompt injection ───────────────────────────
    for pattern in _INJECTION_PATTERNS:
        match = pattern.search(text)
        if match:
            result["injection_detected"] = True
            result["safe"] = False
            result["threats"].append({
                "category": "PromptInjection",
                "severity": "critical",
                "description": f"Prompt injection attempt detected: '{match.group()}'",
                "matched_text": match.group(),
            })

    # ── Check for PII ────────────────────────────────────────
    for pii_type, (pattern, label) in _PII_PATTERNS.items():
        matches = pattern.findall(text)
        if matches:
            result["pii_detected"].append({
                "type": pii_type,
                "label": label,
                "count": len(matches),
            })
            # PII in output is more concerning than in input
            severity = "high" if content_type == "output" else "medium"
            result["threats"].append({
                "category": "PII_Exposure",
                "severity": severity,
                "description": f"{label} detected ({len(matches)} instance{'s' if len(matches) > 1 else ''})",
                "matched_text": f"[{label} REDACTED]",
            })

    # ── Check for harmful content ────────────────────────────
    for pattern in _HARMFUL_PATTERNS:
        match = pattern.search(text)
        if match:
            result["harmful_content"] = True
            result["safe"] = False
            result["threats"].append({
                "category": "HarmfulContent",
                "severity": "critical",
                "description": f"Potentially harmful content detected",
                "matched_text": match.group(),
            })

    # ── Azure AI Content Safety (always when endpoint configured) ──
    if settings.azure_content_safety.endpoint:
        try:
            azure_result = await _azure_content_safety_scan(text)
            if azure_result.get("threats"):
                result["threats"].extend(azure_result["threats"])
                if any(t["severity"] == "critical" for t in azure_result["threats"]):
                    result["safe"] = False
            # Enrich result with Azure category scores
            if azure_result.get("category_scores"):
                result["azure_category_scores"] = azure_result["category_scores"]
        except Exception as e:
            logger.warning("Azure Content Safety API error (falling back to rules): %s", e)

    # ── Calculate risk score ─────────────────────────────────
    if result["threats"]:
        severity_scores = {"low": 0.2, "medium": 0.5, "high": 0.75, "critical": 1.0}
        max_severity = max(severity_scores.get(t["severity"], 0.5) for t in result["threats"])
        result["risk_score"] = round(max_severity, 2)
        if max_severity >= 0.75:
            result["safe"] = False

    return result


async def _azure_content_safety_scan(text: str) -> dict[str, Any]:
    """Call Azure AI Content Safety API for deep content analysis."""
    import httpx
    from azure.identity import DefaultAzureCredential

    endpoint = settings.azure_content_safety.endpoint.rstrip("/")
    credential = DefaultAzureCredential()
    token = credential.get_token("https://cognitiveservices.azure.com/.default")

    async with httpx.AsyncClient(timeout=10.0) as client:
        response = await client.post(
            f"{endpoint}/contentsafety/text:analyze?api-version=2024-09-01",
            headers={
                "Authorization": f"Bearer {token.token}",
                "Content-Type": "application/json",
            },
            json={
                "text": text[:10000],  # API limit
                "categories": ["Hate", "SelfHarm", "Sexual", "Violence"],
                "outputType": "FourSeverityLevels",
            },
        )
        response.raise_for_status()
        data = response.json()

    threats = []
    category_scores = {}
    severity_map = {0: "low", 2: "medium", 4: "high", 6: "critical"}

    for cat_result in data.get("categoriesAnalysis", []):
        severity_level = cat_result.get("severity", 0)
        category_scores[cat_result["category"]] = severity_level
        if severity_level >= 2:
            threats.append({
                "category": f"Azure_{cat_result['category']}",
                "severity": severity_map.get(severity_level, "medium"),
                "description": f"Azure Content Safety: {cat_result['category']} (severity {severity_level})",
                "matched_text": "[Azure AI flagged]",
            })

    return {"threats": threats, "category_scores": category_scores}
